config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'geocoder/findaddress'
  resources :pets do
      get :search, on: :collection
  end

  devise_for :users, controllers:{
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }
  resources :users do
      get :show
  end

  root to: 'pets#index'
  resources :interactions, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :user_id, presence: true
  validates :photo, presence: true
  mount_uploaders :photo, PhotoUploader
  belongs_to :user
  enum size: [:enano, :chico, :mediano, :grande, :gigante]
  enum age: ["De 1 a 4 meses", "De 5 a 8 meses", "De 9 a 12 meses",
   "2 a 3 Años", "4 a 5 Años", "6 a 7 Años","8 años o más"]
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :search]
  load_and_authorize_resource


  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.first
  end
  # GET /pets/new
  def new
    @pet = Pet.new
  end

  def search
    @pets = Pet.all
    @interaction = Interaction.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Has Registrado a tu Mascota.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit({photo:[]}, :name, :specie, :breed, :municipal_record, :vaccines, :sex, :size, :age)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> No puedes crear mascota:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Foto_Mascota %>
    <p class="choose"><%= form.file_field :photo, multiple: true%></p>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Mascota %>
    <%= form.select :specie, [["Perro"], ["Gato"],["Erizo"], ["Conejo"],
    ["Ave"], ["Serpiente"],["Iguana"],["Roedor"],["Hurón"],["Hamster"]] %>
  </div>

  <div class="field">
    <%= form.label :Registro_Municipal %>
    <%= form.check_box :municipal_record %>
  </div>

  <div class="field">
    <%= form.label :Vacunas_al_día %>
    <%= form.check_box :vaccines %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.select :sex, [["M", 0],["F", 1]] %>
  </div>

  <div class="field">
    <%= form.label :Tamaño %>
    <%= form.select :size, Pet.sizes.keys %>
  </div>

  <div class="field">
    <%= form.label :Rango_Edad %>
    <%= form.select :age, Pet.ages.keys %>
  </div>

  <!-- <div class="field">
    <%= form.label :descripción %>
    <%= form.text_area :description %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<!-- welcome -->
<div class="welcome">
  <div class="container">
    <div class="col-md-6 w3ls_welcome_right">
      <div class="flexslider">
        <ul class="slides">
          <li>
            <div class="agileits_w3layouts_welcome_grid">
              <img src="http://www.cvgalapago.es/blog/wp-content/uploads/2016/11/img_la_alimentacion_del_erizo_africano_20306_600-300x300.jpg" alt=" " class="img-responsive" />
             </div>
            </li>
            <li>
              <div class="agileits_w3layouts_welcome_grid">
                <img src="http://www.rodentia.es/blog/wp-content/uploads/2015/09/Retar-a-un-Perro-300x300.jpg" alt=" " class="img-responsive" />
              </div>
            </li>
            <li>
              <div class="agileits_w3layouts_welcome_grid">
                <img src="https://mazovacy.files.wordpress.com/2013/10/lil-bub-2-300x300.jpg" alt=" " class="img-responsive" />
              </div>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-md-6 w3ls_welcome_left">
        <div class="w3ls_welcome_right1">
          <h3 class="agileits-title">Conoce Animalove</h3>
          <h6>La mejor forma de encontrar amigos a tus mascotas
            <span> Felicidad para tu mascota </span> Entretención para ellos. </h6>
            <p>Contacta amigos para tus mascotas;
              Encuentra amigos para tus animales haz Match y diviértete.
              Encuentra personas que quieran amigos/pareja para su mascota,
              Para poder contactarte con otro dueño, tienen que hacer ¡Match! mutuo,
              para poder acceder a la información del Usuario. Conectate con los dueños,

              te damos la bienvenida a Animalove..</p>
              <div class="w3l_more">
                <a href="#" class="button button--nina" data-text="Conoce más" data-toggle="modal" data-target="#myModal">
                  <span>L</span><span>e</span><span>a</span><span>n</span> <span>m</span><span>o</span><span>r</span><span>e</span>
                </a>
              </div>
            </div>
            <div class="clearfix"> </div>
          </div>
          <div class="clearfix"> </div>
        </div>
      </div>

      <!-- //welcome -->

      <!-- //Geolocalización -->

      <!-- <div id="demo"> </div>
      <button onclick="getLocation()">Try It</button> -->

      <!-- //Geolocalización -->

      <!-- banner -->
      <div class="w3ls-banner jarallax">
        <div class="w3lsbanner-info">
          <!-- header -->
          <div class="header cuerpo">
            <div class="container">
              <div class="agile_header_grid">
                <div class="header-mdl agileits-logo"><!-- header-two -->
                  <h1><a href="index.html">Animalove❤</a></h1>
                </div>
                <div class="agileits_w3layouts_sign_in">
                  <ul>
                    <li><a href="https://www.facebook.com/AmistaParaTusMascotas/?modal=admin_todo_tour"
                      data-toggle="modal" class="play-icon">Facebook</a></li>
                    <li>Contacto : <span>(+569)56679568</span></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <!-- //header -->
          <!-- banner-text -->
          <div class="banner-text agileinfo">
            <div class="container">
              <div class="agile_banner_info">
                <div class="agile_banner_info1">
                  <h6>Contacta amigos para tus mascotas en un abrir y cerrar de ojos </h6>
                  <div id="typed-strings" class="agileits_w3layouts_strings">
                    <p>Bienvenido a<i> Animalove</i></p>
                    <p><i>Mascotas</i>De todas partes</p>
                    <p>Diversión <i>Para ellos</i></p>
                  </div>
                  <span id="typed" style="white-space:pre;"></span>
                </div>
              </div>
              <div class="agile_social_icons_banner">
                <ul class="agileits_social_list">
                  <li><a href="https://www.facebook.com/AmistaParaTusMascotas/?modal=admin_todo_tour" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <!-- //banner-text -->
        </div>
      </div>
      <!-- //banner -->
      <!-- banner-bottom -->
      <div class="banner-bottom">
        <div class="col-md-4 bnr-agileitsgrids">
          <div class="agileinfo_banner_bottom_pos">
            <div class="w3_agileits_banner_bottom_pos_grid">
              <div class="col-xs-4 wthree_banner_bottom_grid_left">
                <div class="agile_banner_bottom_grid_left_grid hvr-radial-out">
                  <i class="fa fa-clone" aria-hidden="true"></i>
                </div>
              </div>
              <div class="col-xs-8 wthree_banner_bottom_grid_right">
                <h4>Animalove</h4>
                <p>El mejor sitio para encontrar amigos para tus mascotas, subscribete.</p>
              </div>
              <div class="clearfix"> </div>
            </div>
          </div>
        </div>
        <div class="col-md-4 bnr-agileitsgrids w3grid1">
          <div class="agileinfo_banner_bottom_pos">
            <div class="w3_agileits_banner_bottom_pos_grid">
              <div class="col-xs-4 wthree_banner_bottom_grid_left">
                <div class="agile_banner_bottom_grid_left_grid hvr-radial-out">
                  <i class="fa fa-heart-o" aria-hidden="true"></i>
                </div>
              </div>
              <div class="col-xs-8 wthree_banner_bottom_grid_right">
                <h4>Entretención</h4>
                <p>Contactate con otros dueños, para generar cita, para tu compañero de vida.</p>
              </div>
              <div class="clearfix"> </div>
            </div>
          </div>
        </div>
        <div class="col-md-4 bnr-agileitsgrids w3grid2">
          <div class="agileinfo_banner_bottom_pos">
            <div class="w3_agileits_banner_bottom_pos_grid">
              <div class="col-xs-4 wthree_banner_bottom_grid_left">
                <div class="agile_banner_bottom_grid_left_grid hvr-radial-out">
                  <i class="fa fa-comment-o" aria-hidden="true"></i>
                </div>
              </div>
              <div class="col-xs-8 wthree_banner_bottom_grid_right">
                <h4>Conectate!</h4>
                <p> y preparate para hacer match!, ellos estarán muy felices!!!, ya lo verás.</p>
              </div>
              <div class="clearfix"> </div>
            </div>
          </div>
        </div>
        <div class="clearfix"> </div>
      </div>
      <!-- //banner-bottom -->

      <!-- news letter -->
      <div class="subscribe jarallax">
        <div class="sub-agileinfo">
          <div class="container">
            <h3 class="agileits-title w3title1">Importante</h3>
            <p>Animal Love es una aplicación sana para generar lazos con gente que quiera que su mascota genere una amistad, todos los derechos reservados culquier
              consulta u observación no duden en comunicarse con la mesa de ayuda al +56956679568.</p>
            </div>
          </div>
        </div>
        <!-- //news letter -->
        <!-- footer -->
        <div class="footer">
          <div class="footer-top">
            <div class="container">
              <div class="footer-grids">
                <div class="col-md-3 col-sm-6 footer-logo">
                  <div class="agileits-logo">
                    <h2><a href="index.html">ANIMALOVE</a></h2>
                  </div>
                  <p>Todos tenemos derechos a conocer a otros similares y poder ser feliz a traves de nuevas amistades sanas, que todos seamos felices siempre.</p>
                </div>

                <div class="col-md-3 col-sm-6 footer-grid">
                  <h3>Navigation</h3>
                  <ul>
                    <li><a href="/pets">Inicio</a> </li>
                    <li><a href="/pets/search">Haz Match</a></li>
                    <li><a href="/users/sign_up">Ingresa</a></li>
                  </ul>
                </div>

                <div class="col-md-3 col-sm-6 footer-grid">
                  <h3>Facebook</h3>
                  <ul class="w3agile_footer_grid_list">
                    <li>Contactanos a través de <a href="Facebook"></a>.
                      <span><i class="fa fa-twitter" aria-hidden="true"></i> 02 days ago</span></li>
                      <li>Entra a través de tu facebook<a href="#"></a> Ingresa.
                        <span><i class="fa fa-twitter" aria-hidden="true"></i> 03 days ago</span></li>
                      </ul>
                    </div>

                    <div class="col-md-3 col-sm-6 footer-list">
                      <ul>
                        <p>Hasta que uno no descubre lo que supone amar a un animal,
                          no acaba de comprender lo que es la nobleza y el despertar
                          de unas emociones que pueden llegar a sanarnos el alma.
                          Darle amor a un perro, a un gato o a cualquier ser vivo por pequeño,
                          inquieto y singular que sea, es enriquecernos y descubrir que pueden
                          tener sentimientos tan valiosos como los nuestros..</p>
                        </ul>
                      </div>
                      <div class="clearfix"> </div>
                    </div>
                  </div>
                </div>
                <div class="footer-bottom">
                  <div class="container">
                    <p>© 2018 Animalove. All rights reserved | </p>
                  </div>
                </div>
              </div>
              <!-- //footer -->

              <!-- modal-about -->
              <div class="modal bnr-modal fade" id="myModal" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body modal-spa">
                      <img src="<%=image_path'g2.jpg'%>" class="img-responsive" alt=""/>
                      <h4>Podras buscar millones de amigos para tu mascota</h4>
                      <p>Si encuentras una mascota con las caracteristicas que te gustan, podras darle me gusta, y al hacerse match podras acceder a la información de su dueño y así podras comunicarte con él para planear una cita de juegos para tu mascota :),</p>
                    </div>
                  </div>
                </div>
              </div>
              <!-- //modal-about -->

app/views/pets/new.html.erb
<div class="Registrate">

<h1>Registra tu Mascota</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>
</div>

app/views/pets/search.html.erb
<div class="cambios">

<h1>Mascotas</h1>
<%= link_to 'Registra a tu mascota', new_pet_path, class: "btn btn-primary" %>

<div class="row">
  <div class="container">

  </div>
  <% @pets.each_slice(4) do |row| %>
  <% row.each do |pet| %>
  <div class= "col-md-3">
    <div class ="card">
      <%= image_tag pet.photo.sample.url, class:'card-img-top', size: '200x200' %>
      <div class="body">
      <h4><%="Nombre:"%><%= pet.name %></h4>
        <h5><%="Tipo de Mascota: "%><%= pet.specie %></h5>
        <%="Permiso Municipal:  "%><%if pet.municipal_record == 'f' %>
        <td>Sí</td>
        <%else%>
        <td>No</td>
        <% end %></br>
        <%="Sexo:  "%>  <%if pet.sex == 'f' %>
        <td>masculino</td>
        <%else%>
        <td>femenino</td>
        <% end %></br>
        <%="Posee vacunas al día:  "%><%if pet.vaccines == 'f' %>
        <td>Sí</td>
        <%else%>
        <td>No</td>
        <% end %></br>
        <%="Edad: "%><%= pet.age %></br>
        <%="Tamaño : "%><%= pet.size %></br>
        <!-- <%="Descripción: "%><%= pet.description %> -->

        <%= form_for(@interaction) do |form|  %>
        <%= form.submit %>
        <div class="field">
          <% form.label :user_two_id %>
          <%= form.text_field :user_two_id, value: pet.user.id  %>
          <% link_to 'Show', pet %>
          <% if can?(:destroy, pet) %>
          <%= link_to 'Edit', edit_pet_path(pet) %>
          <%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %>
          <%end%>
        </div>
        <% end %>

      </div>
    </div>
  </div>
  <% end %>
  <div class = "w-100" style="margin-top:20px"> </div>
  <% end %>
</div>
</div>
</div>

<!-- banner -->
<div class="w3ls-banner jarallax">
  <div class="w3lsbanner-info">
    <!-- header -->
    <div class="header cuerpo">
      <div class="container">
        <div class="agile_header_grid">
          <div class="header-mdl agileits-logo"><!-- header-two -->
            <h1><a href="index.html">Animalove❤</a></h1>
          </div>
          <div class="agileits_w3layouts_sign_in">
            <ul>
              <li><a href="https://www.facebook.com/AmistaParaTusMascotas/?modal=admin_todo_tour"
                data-toggle="modal" class="play-icon">Facebook</a></li>
              <li>Contacto : <span>(+569)56679568</span></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- //header -->
    <!-- banner-text -->
    <div class="banner-text agileinfo">
      <div class="container">
        <div class="agile_banner_info">
          <div class="agile_banner_info1">
            <h6>Contacta amigos para tus mascotas en un abrir y cerrar de ojos </h6>
            <div id="typed-strings" class="agileits_w3layouts_strings">
              <p>Bienvenido a<i> Animalove</i></p>
              <p><i>Mascotas</i>De todas partes</p>
              <p>Diversión <i>Para ellos</i></p>
            </div>
            <span id="typed" style="white-space:pre;"></span>
          </div>
        </div>
        <div class="agile_social_icons_banner">
          <ul class="agileits_social_list">
            <li><a href="https://www.facebook.com/AmistaParaTusMascotas/?modal=admin_todo_tour" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
    <!-- //banner-text -->

app/views/pets/show.html.erb
<div class="Mascota_registrada">

<div class="row">

</div>
<p>
  <strong>Foto:</strong></br>
  <%= image_tag @pet.photo[0].url %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Mascota:</strong>
  <%= @pet.specie %>
</p>

<p>
  <strong>Permiso Municipal:</strong>
  <% if @pet.municipal_record == true %>
  si
  <% else %>
  no
  <% end %>
</p>

<p>
  <strong>Vacunas al día:</strong>
  <% if @pet.vaccines == true %>
  si
  <% else %>
  no
  <% end %>
</p>

<p>
  <strong>Sexo:</strong>
  <% if @pet.sex == true %>
  Femenino
  <% else %>
  Masculino
  <% end %>
</p>

<p>
  <strong>Tamaño:</strong>
  <%= @pet.size %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @pet.age %>
</p>

</div>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>
</div>